sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t milindr12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true milindr12/docker-react npm run test
